// lyricsData.js
export const lyrics = [
    { time: 0, text: "" },
    { time: 2, text: "Kaash ye sach hota" },
    { time: 4, text: "lekin tum to kisi aur ke sath ho" },
    { time: 8, text: "koi baat nahi.... isak ye matkab to nahi" },
    { time: 11, text: "ke main tumse pyaar nahi kar sakta" },
    { time: 14, text: "Ab tumse pyaar hai to hai...💖" },
    { time: 17, text: "aur dekho na kitan besharam sa ho gaya hun" },
    { time: 21, text: "tum reply dene ko taiyaar nahi ho" },
    { time: 24, text: "aur main tumse milne ki Hasrat laagaye baith hun" },
    { time: 28, text: "Vaise kahna to bahot kuch hai tumse" },
    { time: 30, text: "lekin tum sunogi nahi" },
    { time: 33, text: "Mere dost mujhase hamesh kahte hain" },
    { time: 36, text: "chhod de nahi milegi vo tujhe" },
    { time: 39, text: "pagal ho jaayega usake piche" },
    { time: 42, text: "Tab maine ek sher likha tha" },
    { time: 44, text: "agar izazat ho to sunau" },
    { time: 48, text: "chhodo suna hi deta hun" },
    { time: 50, text: "ki tumhari aankhon me ek noor sa hai" },
    { time: 55, text: "isliye shayad ye dil majboor sa hai" },
    { time: 60, text: "log kahte hain pagal mat ban" },
    { time: 62, text: "vo nahi milegi tujhe....." },
    { time: 66, text: "maine kaha bina mile mohabbat ki hai usase" },
    { time: 69, text: "pagalpan ab dur kaha hai." },
];
